server:
  port: 18082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guli_stock?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true # 输出sql
  cloud:
    nacos:
       discovery:
         server-addr: localhost:8848
         ip: localhost
  application:
    name: stock-nacos-service